import 'package:quran/quran.dart' as quran;

/// Helpers for localised Quran surah names.
///
/// [getSurahDisplayName] returns the Arabic transliteration (e.g. "Al Fatiha")
/// which is the standard label in both Indonesian and English Islamic usage.
///
/// [getSurahMeaning] returns the translated meaning in the requested language
/// (e.g. "The Opening" / "Pembukaan").
class QuranUtils {
  QuranUtils._();

  /// Arabic transliteration — language-neutral primary label.
  static String getSurahDisplayName(int surahNumber) =>
      quran.getSurahName(surahNumber);

  /// Translated meaning in [isEn ? English : Indonesian].
  static String getSurahMeaning(int surahNumber, {required bool isEn}) {
    if (isEn) return quran.getSurahNameEnglish(surahNumber);
    return _idMeanings[surahNumber] ?? quran.getSurahNameEnglish(surahNumber);
  }

  // Indonesian meanings for all 114 surahs
  static const Map<int, String> _idMeanings = {
    1:   'Pembukaan',
    2:   'Sapi Betina',
    3:   'Keluarga Imran',
    4:   'Wanita',
    5:   'Hidangan',
    6:   'Binatang Ternak',
    7:   'Tempat Tertinggi',
    8:   'Rampasan Perang',
    9:   'Pengampunan',
    10:  'Yunus',
    11:  'Hud',
    12:  'Yusuf',
    13:  'Petir',
    14:  'Ibrahim',
    15:  'Daerah Al-Hijr',
    16:  'Lebah',
    17:  'Perjalanan Malam',
    18:  'Gua',
    19:  'Maryam',
    20:  'Ta Ha',
    21:  'Para Nabi',
    22:  'Ibadah Haji',
    23:  'Orang-orang Beriman',
    24:  'Cahaya',
    25:  'Pembeda',
    26:  'Para Penyair',
    27:  'Semut',
    28:  'Cerita-cerita',
    29:  'Laba-laba',
    30:  'Bangsa Romawi',
    31:  'Luqman',
    32:  'Sujud',
    33:  'Golongan-golongan',
    34:  'Kaum Saba',
    35:  'Pencipta',
    36:  'Ya Sin',
    37:  'Yang Berbaris',
    38:  'Sad',
    39:  'Rombongan-rombongan',
    40:  'Maha Pengampun',
    41:  'Dijelaskan',
    42:  'Musyawarah',
    43:  'Perhiasan Emas',
    44:  'Kabut',
    45:  'Yang Berlutut',
    46:  'Bukit Pasir',
    47:  'Muhammad',
    48:  'Kemenangan',
    49:  'Kamar-kamar',
    50:  'Qaf',
    51:  'Angin yang Menerbangkan',
    52:  'Bukit Sinai',
    53:  'Bintang',
    54:  'Bulan',
    55:  'Yang Maha Pengasih',
    56:  'Hari Kiamat',
    57:  'Besi',
    58:  'Wanita yang Menggugat',
    59:  'Pengusiran',
    60:  'Wanita yang Diuji',
    61:  'Barisan',
    62:  'Hari Jumat',
    63:  'Orang-orang Munafik',
    64:  'Pengungkapan Kesalahan',
    65:  'Talak',
    66:  'Pengharaman',
    67:  'Kerajaan',
    68:  'Pena',
    69:  'Hari Kiamat',
    70:  'Tempat-tempat Naik',
    71:  'Nuh',
    72:  'Jin',
    73:  'Orang yang Berselimut',
    74:  'Orang yang Berkemul',
    75:  'Hari Kiamat',
    76:  'Manusia',
    77:  'Malaikat yang Diutus',
    78:  'Berita Besar',
    79:  'Malaikat yang Mencabut',
    80:  'Bermuka Masam',
    81:  'Penggulungan',
    82:  'Terbelah',
    83:  'Orang-orang yang Curang',
    84:  'Terbelah',
    85:  'Gugusan Bintang',
    86:  'Yang Datang Malam Hari',
    87:  'Yang Maha Tinggi',
    88:  'Hari Kiamat',
    89:  'Fajar',
    90:  'Negeri',
    91:  'Matahari',
    92:  'Malam',
    93:  'Waktu Duha',
    94:  'Kelapangan',
    95:  'Buah Tin',
    96:  'Segumpal Darah',
    97:  'Kemuliaan',
    98:  'Bukti yang Nyata',
    99:  'Kegoncangan',
    100: 'Kuda Perang',
    101: 'Hari Kiamat',
    102: 'Bermegah-megahan',
    103: 'Masa',
    104: 'Pengumpat',
    105: 'Gajah',
    106: 'Suku Quraisy',
    107: 'Barang yang Berguna',
    108: 'Nikmat yang Berlimpah',
    109: 'Orang-orang Kafir',
    110: 'Pertolongan',
    111: 'Sabut',
    112: 'Keikhlasan',
    113: 'Waktu Subuh',
    114: 'Manusia',
  };
}
